### ISSUE TITLE
OpenIMU USB hub disapears from Ubuntu

### ISSUE THREAD

**Issue by GodCed** [introlab/OpenIMU-MiniLogger#20]
OpenIMU USB hub disapears from Ubuntu from time to time.
Seems to be often after programming, sometime after reset with the power switch.

It is necessary to rebind the USB bus in Ubuntu (unplugging and re-plugging is not sufficient) to recover.
For USB 3.0 bus:
```bash
sudo echo -n "0000:03:00.0" | sudo tee /sys/bus/pci/drivers/xhci_hcd/unbind
sudo echo -n "0000:03:00.0" | sudo tee /sys/bus/pci/drivers/xhci_hcd/bind
```

**Comment by doumdi** [comment]
Fixed.
